Resilient-Labs/safe-route

- controllers/auth.js
Title: fix: changed the page render route in the auth controller
- Closes #22
Branch: `22-signin-page-route`
changes the res.render route
none
> fix: changed the page render route in the auth controller

- controllers/posts.js
Title: FIX: changed the routing for the postView.ejs
- Closes #25 
- Related to #[optional]
**Branch: #25-post-view-route
changes to res.render for posts.ejs
none
> FIX: changed the routing for the postView.ejs

- controllers/posts.js
**Title:** Fix(feed): Modified posts.js to render feed, remove logic for previous posts
- Closes #40 
**Branch:** `40-feed-page`
feed.ejs -> Rendered the feed page
> Fix(feed): Modified posts.js

- models/User.js
Title: fix: added necessary properties to UserSchema and got rid of unnecessary properties
- Closes #[26]
**Branch:** `26-user-schema`
Got rid of username. Added zip code, longitude, latitude, first name and last name.
> fix: added necessary properties to UserSchema and got rid of unnecessary properties

- controllers/posts.js
Title: Feat: added upvote feature to post
- Closes #50
**Branch: #50-impliment-upvote-posts
changed likes top upvotes
waiting for posts schema to be be created to add additional like requirements
> Feat: added upvote feature to post

- models/Post.js
**Title:** Fix(Post-schema): Fixed type property to use string, added default for all properties
- Closes #65 
- Related to #27 
**Branch:** `65-define-alert-schema`
- Fixed the type and added defaults
> Fix(Post-schema): Fixed type property to use string, added defaults

- controllers/posts.js
Title:Added downVotePost basic functionality
- Closes #51
Branch: 51-implement-downvote-functionality
Basic down vote functionality route with findOneAndUpdate(). Increases down vote by one. Res.redirect to  (`/post/${req.params.id}`).
Added simple notes about in code for next step updates.
> build: Added downVotePost basic functionality

- public/css/headerFooter.css
- views/landing.ejs
- views/partials/footer.ejs
- views/partials/header.ejs
- Closes #80
- Related to #80 
Branch: 80-optimize-refactor
What’s Included:
- Refactored landing.ejs to use reusable header.ejs and footer.ejs partials
- Created headerFooter.css with shared header and footer styles
- Implemented dynamic EJS logic for safe currentPage and user references
- Confirmed functional layout on localhost:2121 & landing.ejs
Notes for Reviewers:
- This PR only affects the landing page structure and layout
- No backend logic or teammate code was touched
- Tested locally and confirmed visual match with mapView nav/header/footer
> feat: Refactor - Landing Page with Header/Footer Partials and Shared Styling

- controllers/auth.js
Title: fix: fixed remaining login routes, passed the logged-in user data to the view
- Closes #86
**Branch:** `86-update-authjs-file`
I changed login routes to reflect the signin naming. I passed the logged-in user data to the view so it can bed referenced  in the template.
> fix: fixed remaining login routes, passed the logged-in user data to the view

- controllers/posts.js
Title: feat: Updated downvote and deletePost functionality
- Closes #82
Branch: 82-implement-delete-logic
Added functionality for downvotePost and deletePost. 
N/A
> feat: Updated downvote and deletePost functionality

- views/signin.ejs
- views/signup.ejs
- Closes #98 
- Related to #36 #34  
**Branch:** 98-signupejs-add-confirm
-Added confirm password input field in the signup.ejs
-Made sure labels aligned between signup.ejs and signin.ejs
> fix: added new input field to confirm password and aligned labels

- controllers/posts.js
**Title:** Fix(votes): Fixed response redirects on the votes and bookmark controllers
- Closes #102 
- Related to #51 #50 #76 
**Branch:** `102-fix-post-redirects`
Fixed the redirect causing the site to crash
Redirects on downvotes was crashing because there was a second redirect outside the conditional, user 'back' to redirect to referrer
> Fix(votes): Fixed response redirects 

- models/User.js
Title: changed fistName to firstName in models/User.js
- Closes #101 
What’s Included:
fix firstName property in User Schema
> fix: changed fistName to firstName in models/User.js

- controllers/comments.js
- models/Comment.js
- routes/comments.js
- server.js
Title: feat(comments): Implement full CRUD for post comments
- Closes #57 
Branch: 57-implement-full-crud
This PR introduces full Create, Read, Update, and Delete (CRUD) functionality for comments associated with posts.
Notes for Reviewers:
Reviewed with Layomi. Everything worked!
> feat(Implement Full CRUD): Implemented FULL crud for post comments!

- public/mapView(main).js
- views/mapview.ejs
- views/partials/footer.ejs
- views/partials/header.ejs
- Closes #110 
- Related to #107 
**Branch:** 110-mapviewejs-fix-layout
Ensure the entire page renders as expected without visual or functional errors
-Format the dropdown inside the alert submission form so options appear and are readable -Confirm that the Leaflet.js script tag is properly linked and loading at the bottom of the file -Verify that the correct CSS file is included and applied via the header.ejs partial
Notes for Reviewers:
This is a vim swap file warning that occurs when you're trying to edit a Git merge message file. Here's what's happening and how to resolve it:
What this means:
You have an interrupted Git merge in progress
A previous vim session editing the merge message either crashed or was interrupted
The actual file is newer …
> 110 mapviewejs fix layout

- views/post.ejs
Closes #122 
**Branch**: 122-postejs-complete-content
**What’s Included:**
- Displays title, image, address, and city from Post schema
- Shows created date and description
- Includes upvote and downvote forms with Font Awesome icons
- Conditionally shows delete button if user is post owner
- Lists all comments with like and delete functionality
- Adds form to submit a new comment
- Renders return links to Map and Feed pages
- Uses commentText per schema and follows backend structure
**Notes for Reviewers**
**- Will add visual feedback (e.g. green/red icon states) to show if user has already upvoted or downvoted**
**- Plan to display login-required alerts for upvote/downvote/comment actions using npm toast or similar message prompts**
- Styling to be added on separate …
> feat: finish post.ejs content and logic ticket

- public/transition.js
- views/feed.ejs
- views/partials/footer.ejs
Title: Added upvote/downvote to feed.ejs.
- Closes #106
**Branch:** `106-implement-vbf-logic`
Since several files needed to be changed I only did the first part of the ticket. The bookmark and filter logic should be broken up into 2 more tickets and updated for new requirements. Added upvote/downvote to feed.ejs as forms but will change to ajax so numbers will be updated without reload. Converted to current fontAwesome. Added font awesome script in footer.  Added transition.js file to switch to AJAX later. Will need to pass JSON in the backend controller.
> feat: Added upvote/downvote to feed.ejs. 

- public/css/landing.css
- views/landing.ejs
- Closes #92
- Related to #28
**Branch:** 92-landing-page-styling
- styled landing ejs
- created stylesheet for it
- link on top of landing.ejs 
will be adding responsive features at a later ticket
> style:applied vanilla css for landing ejs

- controllers/posts.js
- models/Post.js
- routes/posts.js
**Title:** Adds Geospatial Indexing to posts, adds getFeed Controller and modifies createPost controller
- Closes #136 
**Branch:** `136-retrieve-by-location`
This PR adds geospatial support to the Post model by introducing a location field with a 2dsphere index. It updates the post creation logic to store coordinates in GeoJSON format ([longitude, latitude]) and removes latitude and longitude from being stored as top-level fields. Additionally, it adds location-based filtering and querying for getFeed post controller.
> 136 retrieve by location

- controllers/posts.js
**Title:** getPostPage checks if user exists and return accordingly 
- Closes #153 
**Branch:** `153-fix-getpostpage-controller`
checks if users exists and renders page accordingly
> fix: getPostPage controller to check if user exists

- public/css/landing.css
- Closes #144 
- Related to #92 
**Branch:** 144-landingejs-responsive
- add responsive features for small and large screen
- minor edits to button
> feat:updated landing page responsiveness

- public/css/post.css
- views/post.ejs
**Title:** styled comment section on post.ejs
- Closes #152
**Branch:152-style-comment-postejs
style changes to comment section
none
> Style: added style and layout to post.ejs

- public/mapView(main).js
- routes/comments.js
- routes/posts.js
- server.js
- views/feed.ejs
- views/post.ejs
- views/profile.ejs
**Title:** Overall routing refactoring to follow REST conventions
- Closes #163 
**Branch:** `163-refactor-routes-restconventions`
Refractors routes to follow REST conventions
> fix: overall routing refactoring to follow REST conventions

- controllers/comments.js
**Title:** Added checks for user authentication on comments
- Closes #165 
**Branch:** `165-add-loggedin-checks`
Added user authenticated and user owned checks to comments
> Fix(comments): Added checks for user authentication

- controllers/auth.js
- controllers/map.js
- controllers/posts.js
- middleware/auth.js
- models/Comment.js
- models/User.js
- routes/comments.js
- routes/main.js
- routes/posts.js
- server.js
**Title:** Clean backend routes and functions
- Closes #168 
- Related to #165 #166 #167 
**Branch:** `168-cleanup`
Removed comments, extra logs and unused routes
> Cleanup(backend): Cleaned up comments, profile and routes

- controllers/posts.js
**Title:** Filters and Error handling for posts
- Closes #166
- Related to #165 #167 #168 
**Branch:** `166-filter-getFeed`
Added filters to getFeed, handle getFeedPage error with try-catch block
returned error handling for getFeedPage using flash
> Fix(posts): Added filters to getFeed, handle getFeedPage error

- public/css/sign-in-up.css
- Closes #143 
- Related to #100 
**Branch:** 143-signinejs-signupejs-responsive
-Added media queries to be responsive across different screen/viewport sizes
-Made small changes to CSS like border-radius
> feat: added responsive styling/media queries to sign-in-up.css and fixed minor details in css

- controllers/posts.js
Title: Fixed delete button functionality + refactored delete post res logic
Related Issue(s): Closes #183
Branch: 183-fix-delete-post-button
What’s Included:
- Add object requiring _id, isHidden, and isResolved to post variable in getPostPage
- Change method from .find() to .updateMany() for await Comment in deletePost
Notes for Reviewers:
Refactored deletePost to use res.flash
> fix (delete button): Fixed delete button functionality + refactored delete post res logic

- views/feed.ejs
**Title:** Feat(up-down-book): Added functionality for upvoting, downvoting and bookmarking posts
- Closes #181 
- Related to #189 
**Branch:** `181-add-logic`
- Upvoting, downvoting and bookmarking now works without reloading the page with the correct states.
> Feat(up-down-book): Added functionality for upvoting, downvoting and bookmarking posts

- controllers/posts.js
**Title:** Returned updated vote object from mongoose
- Closes #189 
- Related to #181 
**Branch:** `189-return-updated-postobject`
Return updated vote objects with `{ new: true }`
> Fix(update-posts): Returned new vote object from mongoose

- public/css/feed.css
- views/feed.ejs
**Title:** Refactors Feed Page
- Closes #214 
Icons and better UI/UX
> fix: update feed page 

- views/feed.ejs
- views/post.ejs
**Title:** Fix Address unknown 
- Closes #221
> fix: city/address and comments

- public/css/headerFooter.css
- views/partials/header.ejs
Title: fix: logo shows now
- Closes #236
Branch: `236-mq-show-logo`
edited the media query to display the logo on all size screens
> fix: logo shows now

- public/css/headerFooter.css
Title: fixed dropdown menu added hover effect
- Closes #239 
Branch: `239-fix-media-queries`
added transparent top border to dropdown menu to move it down from the nav bar
> 239 fix media queries
